language: node_js

node_js:
  - "10.1"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email: false

install:
  - npm install -g npm@6.0 yarn codecov.io

# command to run tests
script:
  - cd courrier_back_end && yarn && yarn test && yarn coverage
  - cd ../courrier_front_end && yarn && yarn test