version: '3.1'

services:
  api:
    build:
      context: ./courrier_back_end
      dockerfile: Dockerfile
    depends_on:
     - db
    volumes:
      - ./courrier_back_end:/srv/api:rw
      - /srv/api/node_modules
    ports:
     - "9000:9000"

  client:
    build:
      context: ./courrier_front_end
      dockerfile: Dockerfile
    volumes:
      - ./courrier_front_end:/srv/api:rw
      - /srv/api/node_modules
    ports:
     - "3000:3000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dbda
      MYSQL_DATABASE: sequelize_test
      MYSQL_USER: sequelize_test
      MYSQL_PASSWORD: sequelize_test
    volumes:
      - /mnt/sequelize-db-ramdisk:/var/lib/mysql
