version: '3.1'

services:
  api:
    build:
      context: ./courrier_back_end
      dockerfile: Dockerfile
    depends_on:
     - db
    volumes:
      - ./courrier_back_end:/srv/api:rw
    ports:
     - "9000:9000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dbda
      MYSQL_DATABASE: sequelize_test
      MYSQL_USER: sequelize_test
      MYSQL_PASSWORD: sequelize_test
    volumes:
      - /mnt/sequelize-db-ramdisk:/var/lib/mysql
    ports:
      - "8980:3306"